SELECT ROWNUM 序列,
       A.TABLESPACE_NAME 表空间名称,
       ROUND(A.BYTES_ALLOC / 1024 / 1024, 2) 总分配容量_M,
       ROUND(A.BYTES_ALLOC - NVL(B.BYTES_FREE, 0)) 使用_M,
       ROUND(NVL(B.BYTES_FREE, 0) / 1024 / 1024, 2) 现空闲_M,
       100 - ROUND((NVL(B.BYTES_FREE, 0) / A.BYTES_ALLOC) * 100, 2) 使用率,
       TO_CHAR(SYSDATE, 'yyyy-mm-dd HH24:MI:SS') 查时间
  FROM (SELECT F.TABLESPACE_NAME, SUM(F.BYTES) BYTES_ALLOC
          FROM DBA_DATA_FILES F
         GROUP BY F.TABLESPACE_NAME) A,
       (SELECT F.TABLESPACE_NAME, SUM(F.BYTES) BYTES_FREE
          FROM DBA_FREE_SPACE F
         GROUP BY F.TABLESPACE_NAME) B
 WHERE A.TABLESPACE_NAME = B.TABLESPACE_NAME;
